services:
  - type: web
    name: hrms-rag-chatbot
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python scripts/update_db.py

    startCommand: gunicorn main:app -c gunicorn.conf.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.11